
const KEY='haccp_pwa_v1';
const DEF={prodotti:[],temperature:[],frigoriferi:[
{id:'f1',nome:'Frigo Pesce',tipo:'Frigorifero',min:0,max:4,posizione:'Cucina'},
{id:'f2',nome:'Frigo Carne',tipo:'Frigorifero',min:0,max:4,posizione:'Cucina'},
{id:'f3',nome:'Congelatore 1',tipo:'Congelatore',min:-24,max:-18,posizione:'Cucina'}],ssop:[]};
let data=(()=>{try{let s=JSON.parse(localStorage.getItem(KEY)||'{}'),d={...DEF,...s};d.ssop=Array.isArray(d.ssop)?d.ssop:[];d.frigoriferi=Array.isArray(d.frigoriferi)?d.frigoriferi:DEF.frigoriferi;return d}catch{return structuredClone(DEF)}})();
let view='dashboard',ssopMonth=new Date().toISOString().slice(0,7);
const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+''+Math.random();
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>new Date(d+(d.length===10?'T12:00:00':'')).toLocaleDateString('it-IT');
const fmtDT=d=>new Date(d).toLocaleString('it-IT',{dateStyle:'short',timeStyle:'short'});
function daysTo(x){if(!x)return null;let a=new Date();a.setHours(0,0,0,0);let b=new Date(x+'T12:00:00');b.setHours(0,0,0,0);return Math.round((b-a)/86400000)}
function badge(x){let d=daysTo(x);if(d===null)return'<span class="badge">Nessuna scadenza</span>';if(d<0)return`<span class="badge danger">Scaduto da ${-d} gg</span>`;if(d===0)return'<span class="badge danger">Scade oggi</span>';if(d<=3)return`<span class="badge warn">Scade tra ${d} gg</span>`;return`<span class="badge">Scade ${fmt(x)}</span>`}
function lastTemp(fid){return data.temperature.filter(x=>x.frigoId===fid).sort((a,b)=>b.ts.localeCompare(a.ts))[0]}
function out(f,t){return t&&(Number(t.valore)<Number(f.min)||Number(t.valore)>Number(f.max))}
function ssopNC(r){return['attrezzaturePO','attrezzaturePS','igieneAttrezzaturePO','igieneAttrezzaturePS','localiPO','localiPS','igieneLocaliPO','igieneLocaliPS','personale'].some(k=>r[k]==='NC')}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));let e=document.getElementById('view');e.innerHTML=view==='dashboard'?dash():view==='magazzino'?mag():view==='scadenze'?scad():view==='temperature'?temps():view==='attrezzature'?equip():view==='ssop'?ssopView():altro();bind()}
function dash(){let crit=data.prodotti.filter(p=>{let d=daysTo(p.scadenza);return d!==null&&d<=7}).length,today=new Date().toISOString().slice(0,10),done=data.ssop.some(r=>r.data===today);return`<section class="hero"><h2>Buongiorno 👨‍🍳</h2><p>Controllo HACCP rapido della cucina</p></section><div class="grid"><div class="card"><b>Scadenze critiche</b><div class="metric ${crit?'danger':'ok'}">${crit}</div></div><div class="card"><b>SSOP oggi</b><div class="metric ${done?'ok':''}">${done?'✓':'—'}</div><div class="sub">${done?'Compilato':'Da compilare'}</div></div></div><div class="title"><h2>Temperature</h2><button data-a="newT">+ Registra</button></div><div class="grid">${data.frigoriferi.map(f=>{let t=lastTemp(f.id);return`<div class="card"><b>${f.tipo==='Congelatore'?'❄️':'🧊'} ${esc(f.nome)}</b><div class="metric ${out(f,t)?'danger':'ok'}">${t?t.valore.toFixed(1)+' °C':'--'}</div><div class="sub">${f.min}/${f.max} °C</div></div>`}).join('')}</div><div class="title"><h2>Azioni rapide</h2></div><div class="grid"><button data-a="newP">➕ Nuovo prodotto</button><button class="ghost" data-a="goSSOP">🧼 Controllo SSOP</button></div>`}
function inv(items){return items.length?items.map(p=>`<div class="item"><div class="icon">📦</div><div class="grow"><div class="name">${esc(p.nome)}</div><div class="sub">${esc(p.categoria)} • Lotto ${esc(p.lotto)}</div>${badge(p.scadenza)}</div><button class="dangerBtn" data-del="${p.id}">✕</button></div>`).join(''):'<div class="empty">Nessun prodotto.</div>'}
function mag(){return`<div class="title"><h2>Magazzino</h2><button data-a="newP">+ Nuovo</button></div><input id="search" class="search" placeholder="Cerca prodotto, lotto..."><div id="inv" class="list" style="margin-top:12px">${inv(data.prodotti)}</div>`}
function scad(){return`<div class="title"><h2>Scadenze</h2></div><div class="list">${inv([...data.prodotti].filter(p=>p.scadenza).sort((a,b)=>a.scadenza.localeCompare(b.scadenza)))}</div>`}
function temps(){return`<div class="title"><h2>Registro temperature</h2><button data-a="newT">+ Registra</button></div><div class="list">${[...data.temperature].sort((a,b)=>b.ts.localeCompare(a.ts)).map(t=>{let f=data.frigoriferi.find(x=>x.id===t.frigoId);return`<div class="item"><div class="icon">🌡️</div><div class="grow"><div class="name">${esc(f?.nome||'Attrezzatura')}</div><div class="sub">${fmtDT(t.ts)}</div><span class="badge ${f&&out(f,t)?'danger':''}">${t.valore.toFixed(1)} °C</span></div></div>`}).join('')||'<div class="empty">Nessuna temperatura.</div>'}</div>`}
function equip(){let card=f=>`<div class="item"><div class="icon">${f.tipo==='Congelatore'?'❄️':'🧊'}</div><div class="grow"><div class="name">${esc(f.nome)}</div><div class="sub">${esc(f.tipo)} • ${f.min}/${f.max} °C • ${esc(f.posizione||'')}</div></div><button class="ghost" data-edit="${f.id}">✏️</button><button class="dangerBtn" data-del-eq="${f.id}">✕</button></div>`;return`<div class="title"><h2>Attrezzature</h2><button data-a="newE">+ Aggiungi</button></div><div class="list">${data.frigoriferi.map(card).join('')}</div>`}
function ssopView(){let[y,m]=ssopMonth.split('-').map(Number),n=new Date(y,m,0).getDate(),rows='';for(let d=1;d<=n;d++){let dt=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`,r=data.ssop.find(x=>x.data===dt);rows+=`<div class="item"><div class="icon">${r?(ssopNC(r)?'⚠️':'✅'):'📋'}</div><div class="grow"><div class="name">${fmt(dt)}</div><div class="sub">${r?(ssopNC(r)?'Presente NC':'Tutto conforme'):'Non compilato'}</div></div><button data-ssop="${dt}">${r?'Apri':'Compila'}</button></div>`}return`<div class="title"><h2>Controllo SSOP</h2><button data-a="ssopPDF">PDF</button></div><div class="card"><b>C = Conforme • NC = Non Conforme</b><div class="sub">PO = Preoperativa • PS = Postoperativa</div></div><div class="title"><h2>Mese</h2></div><input id="ssopMonth" type="month" value="${ssopMonth}"><div class="list" style="margin-top:12px">${rows}</div>`}
function altro(){return`<div class="title"><h2>Altro</h2></div><div class="list"><div class="item"><div class="icon">🧼</div><div class="grow"><div class="name">Controllo SSOP</div><div class="sub">Pre/post operativo, conformità e azioni correttive.</div></div><button data-a="goSSOP">Apri</button></div><div class="item"><div class="icon">🧊</div><div class="grow"><div class="name">Frigoriferi e congelatori</div></div><button data-a="goE">Gestisci</button></div><div class="item"><div class="icon">💾</div><div class="grow"><div class="name">Backup dati</div></div><button data-a="backup">Esporta</button></div></div>`}
function bind(){document.querySelectorAll('[data-a="newP"]').forEach(b=>b.onclick=productModal);document.querySelectorAll('[data-a="newT"]').forEach(b=>b.onclick=tempModal);document.querySelectorAll('[data-a="newE"]').forEach(b=>b.onclick=()=>equipModal());document.querySelectorAll('[data-a="goE"]').forEach(b=>b.onclick=()=>{view='attrezzature';render()});document.querySelectorAll('[data-a="goSSOP"]').forEach(b=>b.onclick=()=>{view='ssop';render()});document.querySelectorAll('[data-a="ssopPDF"]').forEach(b=>b.onclick=ssopPDF);document.querySelectorAll('[data-a="backup"]').forEach(b=>b.onclick=backup);document.querySelectorAll('[data-ssop]').forEach(b=>b.onclick=()=>ssopModal(b.dataset.ssop));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>equipModal(data.frigoriferi.find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-del-eq]').forEach(b=>b.onclick=()=>{if(confirm('Eliminare attrezzatura?')){data.frigoriferi=data.frigoriferi.filter(x=>x.id!==b.dataset.delEq);save();render()}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{data.prodotti=data.prodotti.filter(x=>x.id!==b.dataset.del);save();render()});let sm=document.getElementById('ssopMonth');if(sm)sm.onchange=()=>{ssopMonth=sm.value;render()}}
function productModal(){let m=document.getElementById('modal'),f=document.getElementById('modalForm');f.className='modal';f.innerHTML=`<h2>Nuovo prodotto</h2><div class="form"><label>Nome<input name="nome" required></label><label>Categoria<input name="cat"></label><label>Lotto<input name="lotto" required></label><label>Scadenza<input type="date" name="scad"></label></div><div class="actions"><button type="button" class="ghost" id="cancel">Annulla</button><button>Salva</button></div>`;f.onsubmit=e=>{e.preventDefault();let x=new FormData(f);data.prodotti.push({id:id(),nome:x.get('nome'),categoria:x.get('cat'),lotto:x.get('lotto'),scadenza:x.get('scad')});save();m.close();render()};f.querySelector('#cancel').onclick=()=>m.close();m.showModal()}
function tempModal(){if(!data.frigoriferi.length)return alert('Aggiungi prima un frigorifero o congelatore.');let m=document.getElementById('modal'),f=document.getElementById('modalForm');f.className='modal';f.innerHTML=`<h2>Registra temperatura</h2><div class="form"><label class="full">Attrezzatura<select name="frigo">${data.frigoriferi.map(x=>`<option value="${x.id}">${esc(x.nome)} (${x.min}/${x.max} °C)</option>`).join('')}</select></label><label>Temperatura °C<input name="val" required></label><label>Operatore<input name="op"></label><label class="full">Note<textarea name="note"></textarea></label></div><div class="actions"><button type="button" class="ghost" id="cancel">Annulla</button><button>Salva</button></div>`;f.onsubmit=e=>{e.preventDefault();let x=new FormData(f),v=parseFloat(String(x.get('val')).replace(',','.'));if(Number.isNaN(v))return alert('Temperatura non valida');data.temperature.push({id:id(),frigoId:x.get('frigo'),valore:v,operatore:x.get('op'),note:x.get('note'),ts:new Date().toISOString()});save();m.close();render()};f.querySelector('#cancel').onclick=()=>m.close();m.showModal()}
function equipModal(ex=null){let m=document.getElementById('modal'),f=document.getElementById('modalForm');f.className='modal';f.innerHTML=`<h2>${ex?'Modifica':'Nuova'} attrezzatura</h2><div class="form"><label class="full">Nome<input name="nome" required value="${esc(ex?.nome||'')}"></label><label>Tipo<select name="tipo"><option ${ex?.tipo==='Frigorifero'?'selected':''}>Frigorifero</option><option ${ex?.tipo==='Congelatore'?'selected':''}>Congelatore</option></select></label><label>Posizione<input name="pos" value="${esc(ex?.posizione||'')}"></label><label>Min °C<input name="min" value="${ex?.min??0}"></label><label>Max °C<input name="max" value="${ex?.max??4}"></label></div><div class="actions"><button type="button" class="ghost" id="cancel">Annulla</button><button>Salva</button></div>`;f.onsubmit=e=>{e.preventDefault();let x=new FormData(f),o={id:ex?.id||id(),nome:x.get('nome'),tipo:x.get('tipo'),posizione:x.get('pos'),min:parseFloat(x.get('min')),max:parseFloat(x.get('max'))};data.frigoriferi=ex?data.frigoriferi.map(z=>z.id===ex.id?o:z):[...data.frigoriferi,o];save();m.close();render()};f.querySelector('#cancel').onclick=()=>m.close();m.showModal()}
function sel(n,l,v=''){return`<label class="full">${l}<select name="${n}"><option value="">—</option><option ${v==='C'?'selected':''}>C</option><option ${v==='NC'?'selected':''}>NC</option></select></label>`}
function ssopModal(dt){let ex=data.ssop.find(x=>x.data===dt)||{data:dt},m=document.getElementById('modal'),f=document.getElementById('modalForm');f.className='modal';f.innerHTML=`<h2>SSOP — ${fmt(dt)}</h2><div class="form">${sel('attrezzaturePO','Idoneità attrezzature — PO',ex.attrezzaturePO)}${sel('attrezzaturePS','Idoneità attrezzature — PS',ex.attrezzaturePS)}${sel('igieneAttrezzaturePO','Igiene attrezzature — PO',ex.igieneAttrezzaturePO)}${sel('igieneAttrezzaturePS','Igiene attrezzature — PS',ex.igieneAttrezzaturePS)}${sel('localiPO','Idoneità locali — PO',ex.localiPO)}${sel('localiPS','Idoneità locali — PS',ex.localiPS)}${sel('igieneLocaliPO','Igiene locali — PO',ex.igieneLocaliPO)}${sel('igieneLocaliPS','Igiene locali — PS',ex.igieneLocaliPS)}${sel('personale','Igiene del personale',ex.personale)}<label class="full">Verificatore / firma<input name="ver" value="${esc(ex.verificatore||'')}"></label><label class="full">Non conformità<textarea name="nc">${esc(ex.nonConformita||'')}</textarea></label><label class="full">Azione correttiva<textarea name="ac">${esc(ex.azioneCorrettiva||'')}</textarea></label></div><div class="actions"><button type="button" class="ghost" id="cancel">Annulla</button><button>Salva</button></div>`;f.onsubmit=e=>{e.preventDefault();let x=new FormData(f),r={id:ex.id||id(),data:dt,attrezzaturePO:x.get('attrezzaturePO'),attrezzaturePS:x.get('attrezzaturePS'),igieneAttrezzaturePO:x.get('igieneAttrezzaturePO'),igieneAttrezzaturePS:x.get('igieneAttrezzaturePS'),localiPO:x.get('localiPO'),localiPS:x.get('localiPS'),igieneLocaliPO:x.get('igieneLocaliPO'),igieneLocaliPS:x.get('igieneLocaliPS'),personale:x.get('personale'),verificatore:x.get('ver'),nonConformita:x.get('nc'),azioneCorrettiva:x.get('ac')};if(ssopNC(r)&&(!r.nonConformita||!r.azioneCorrettiva))return alert('Con una NC devi indicare non conformità e azione correttiva.');data.ssop=data.ssop.filter(z=>z.data!==dt);data.ssop.push(r);save();m.close();render()};f.querySelector('#cancel').onclick=()=>m.close();m.showModal()}
function ssopPDF(){let rows=data.ssop.filter(r=>r.data.startsWith(ssopMonth)).sort((a,b)=>a.data.localeCompare(b.data)),w=open('','_blank'),v=x=>x||'—';w.document.write(`<html><head><style>body{font-family:Arial;padding:18px;font-size:10px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #777;padding:4px;text-align:center}</style></head><body><h1>CONTROLLO SSOP</h1><h2>${ssopMonth}</h2><table><tr><th>Giorno</th><th>Id.Att PO</th><th>Id.Att PS</th><th>Ig.Att PO</th><th>Ig.Att PS</th><th>Id.Loc PO</th><th>Id.Loc PS</th><th>Ig.Loc PO</th><th>Ig.Loc PS</th><th>Pers.</th><th>Verificatore</th></tr>${rows.map(r=>`<tr><td>${Number(r.data.slice(-2))}</td><td>${v(r.attrezzaturePO)}</td><td>${v(r.attrezzaturePS)}</td><td>${v(r.igieneAttrezzaturePO)}</td><td>${v(r.igieneAttrezzaturePS)}</td><td>${v(r.localiPO)}</td><td>${v(r.localiPS)}</td><td>${v(r.igieneLocaliPO)}</td><td>${v(r.igieneLocaliPS)}</td><td>${v(r.personale)}</td><td>${esc(r.verificatore)}</td></tr>`).join('')}</table><h3>NC e azioni correttive</h3>${rows.filter(ssopNC).map(r=>`<p><b>${fmt(r.data)}</b><br>NC: ${esc(r.nonConformita)}<br>Azione: ${esc(r.azioneCorrettiva)}</p>`).join('')||'<p>Nessuna NC.</p>'}<script>onload=()=>print()</script></body></html>`);w.document.close()}
function backup(){let b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='haccp_backup.json';a.click()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
render();
